#!/bin/bash

docker build \
  --build-arg PUBLIC_WS_PROTO="ws" \
  --build-arg PUBLIC_WS_HOST="127.0.0.1" \
  --build-arg PUBLIC_WS_PORT="9090" \
  --build-arg PUBLIC_WEB_PROTO="http" \
  --build-arg PUBLIC_WEB_HOST="127.0.0.1" \
  --build-arg PUBLIC_WEB_PORT="3000" \
  --build-arg PUBLIC_WEB_DEBUG_PORT="5173" \
  --file .docker/front-end.Dockerfile \
  --tag sched-front-end:latest \
  .
