name: CI/CD

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache-dependency-path: 'pnpm-lock.yaml'
          check-latest: false
          # cache: 'pnpm'

      - name: install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 7.23.0
          run_install: false

      - name: pnpm install
        run: pnpm --recursive install

      - name: run tests
        run: pnpm --recursive test

  dockerize-front-end:
    runs-on: ubuntu-latest
    needs: [run-specs]
    steps:
      - uses: actions/checkout@v3
      - name: dockerize front-end
        env:
          PUBLIC_WS_PROTO: "ws"
          PUBLIC_WS_HOST: "127.0.0.1"
          PUBLIC_WS_PORT: "9090"
          PUBLIC_WEB_PROTO: "http"
          PUBLIC_WEB_HOST: "127.0.0.1"
          PUBLIC_WEB_PORT: "3000"
          PUBLIC_WEB_DEBUG_PORT: "5173"
        run: |
          echo "building docker image for the front-end"
          docker build \
            --build-arg PUBLIC_WS_PROTO=$PUBLIC_WS_PROTO \
            --build-arg PUBLIC_WS_HOST=$PUBLIC_WS_HOST \
            --build-arg PUBLIC_WS_PORT=$PUBLIC_WS_PORT \
            --build-arg PUBLIC_WEB_PROTO=$PUBLIC_WEB_PROTO \
            --build-arg PUBLIC_WEB_HOST=$PUBLIC_WEB_HOST \
            --build-arg PUBLIC_WEB_PORT=$PUBLIC_WEB_PORT \
            --build-arg PUBLIC_WEB_DEBUG_PORT=$PUBLIC_WEB_DEBUG_PORT \
            --file ./.docker/front-end.Dockerfile \
            --tag sched-front-end:latest \
            .

        