name: Node.js CI

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache-dependency-path: 'pnpm-lock.yaml'
          check-latest: false
          # cache: 'pnpm'

      - name: install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
          run_install: false

      - name: pnpm install
        run: pnpm --recursive install

      - name: run tests
        run: pnpm --recursive test
